name: flutter_gadgetbox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.5"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  image_picker: ^0.8.6
  json_serializable: ^6.3.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  pedantic_mono: ^1.19.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

